# Generated by Django 4.2.4 on 2024-12-01 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0004_message_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='budget',
            new_name='max_budget',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='created_at',
            new_name='posted_on',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('design', 'Graphic Design'), ('writing', 'Content Writing'), ('seo', 'SEO Optimization'), ('marketing', 'Digital Marketing')], default='website developement', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='min_budget',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.JSONField(default='python', help_text="List of skills required, e.g., ['Python', 'Django']"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed Price')], default='remote', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
