# Generated by Django 5.1.4 on 2024-12-09 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_tag_remove_jobposting_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
