# Generated by Django 5.1.4 on 2024-12-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_jobposting_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about', 'About Us'), ('contact_us', 'Contact Us'), ('features', 'Features'), ('terms_and_conditions', 'Terms and Conditions'), ('privacy_policy', 'Privacy Policy'), ('faq', 'FAQ')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
