# Generated by Django 5.1.4 on 2024-12-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_staticpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the setting')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Static Page', 'verbose_name_plural': 'Static Pages'},
        ),
        migrations.AddField(
            model_name='staticpage',
            name='system_setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='static_pages', to='admin_panel.systemsetting'),
        ),
    ]
