# Generated by Django 5.1.4 on 2024-12-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_staticpage_system_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticPage',
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
    ]
