# Generated by Django 4.2.4 on 2024-12-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='user',
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='feedbacks',
            field=models.ManyToManyField(to='freelancer.feedback'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
