# Generated by Django 4.2.4 on 2024-12-01 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelancer', '0002_remove_freelancer_user_alter_freelancer_feedbacks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='user',
            field=models.OneToOneField(default='gideon', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='feedbacks',
            field=models.ManyToManyField(blank=True, related_name='freelancer_feedbacks', to='freelancer.feedback'),
        ),
    ]
