# Generated by Django 5.1.4 on 2024-12-06 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='active_jobs',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='completed_jobs',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='feedbacks',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='feedback',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='freelancer',
            field=models.ForeignKey(default='nexus', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='freelancer.freelancer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='i am a software developer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default='main', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='freelancer.freelancer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Available', 'Available'), ('Pending', 'Pending')], default='Available', max_length=20),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
