# Generated by Django 5.1.4 on 2024-12-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='job',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='freelancers', to='freelancer.job'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
