# Generated by Django 5.1.4 on 2024-12-09 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_remove_job_deadline_remove_job_freelancer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='freelancer.freelancer'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Available', 'Available'), ('Pending', 'Pending')], default='Available', max_length=20),
        ),
    ]
