# Generated by Django 5.1.4 on 2024-12-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_remove_freelancer_jobs_job_deadline_job_freelancer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
